### ISSUE TITLE
Dúvidas - CubeHash

### ISSUE THREAD

**Issue by rphms8** [fccoelho/Curso_Blockchain#11]
Professor, não faço a menor ideia de como progredir.

In these notebook, as part of the course at https://github.com/fccoelho/Curso_Blockchain, ministered by professor Flávio Codeço Coelho, I will implement CubeHash, a cryptographic hash function.

`i=10
r=10
b=10
f=10
h=24
m="secret password"

import numpy as np

if b>128:
    print("b must be smaller then or equall to 128")
elif np.remainder(h,8)!=0 or (h/8)>64:
    print("h must be a multiple of 8 and smaller then 512")
else:
    print("CubeHash"+ str(i) + "+" + str(r) + "/" + str(b) + "+" + str(f) + "-" + str(h))
    
`

**Comment by hanelore** [comment]
I am not a student in this class, but maybe this can help: 

http://cubehash.cr.yp.to/index.html

https://github.com/DennisMitchell/cubehash

https://ehash.iaik.tugraz.at/wiki/CubeHash

Congratulations @rphms8 and @fccoelho this seems a excellent class.

**Comment by hanelore** [comment]
Try highlight the code, following this example: https://help.github.com/articles/creating-and-highlighting-code-blocks/

````python
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
import numpy as np

i=10
r=10
b=10
f=10
h=24
m="secret password"

if b>128:
    print("b must be smaller then or equall to 128")
elif np.remainder(h,8)!=0 or (h/8)>64:
    print("h must be a multiple of 8 and smaller then 512")
else:
    print (((i + r) / (b + f)) - h )
    print("CubeHash"+ str(i) + "+" + str(r) + "/" + str(b) + "+" + str(f) + "-" + str(h))
```

**Comment by fccoelho** [comment]
Thanks for the Links @hanelore !

@rphms8, in order to succeed in this implementation, you will need to be able to work with Binary data in Python. If you never did this before I suggest you start by reading this:
https://wiki.python.org/moin/BitArrays
https://wiki.python.org/moin/BitManipulation

We'll talk more in class.
