### ISSUE TITLE
Apresentações

### ISSUE THREAD

**Issue by fccoelho** [fccoelho/Curso_Blockchain#15]
# Calendário de Apresentações 

- Ethereum 2.0
- Litecoin
- Cardano
- Dogecoin
- Polkadot
- Stellar
- Zcash
- Monero
- Theter
- Ripple (XRP)
- Binance coin
- Bitcoin cash
- Theta
- Filecoin
- TRX
- Dai

**Comment by pedrodall** [comment]
Ethereum 2.0
Litecoin
Cardano
Dogecoin
Polkadot
Stellar
Zcash - Pedro Castilho
Monero
Theter
Ripple (XRP)
Binance coin
Bitcoin cash
Theta
Filecoin
TRX
Dai

**Comment by wllsena** [comment]
Ethereum 2.0 - William Sena
Litecoin
Cardano
Dogecoin
Polkadot
Stellar
Zcash - Pedro Castilho
Monero
Theter
Ripple (XRP)
Binance coin
Bitcoin cash
Theta
Filecoin
TRX
Dai

**Comment by dccsillag** [comment]
Ethereum 2.0 - William Sena
Litecoin
Cardano
Dogecoin
Polkadot
Stellar
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter
Ripple (XRP)
Binance coin
Bitcoin cash
Theta
Filecoin
TRX
Dai

**Comment by TLAndrade** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano
Dogecoin
Polkadot
Stellar
Zcash - Pedro Castilho
Monero
Theter
Ripple (XRP)
Binance coin
Bitcoin cash
Theta
Filecoin
TRX
Dai

**Comment by Bissiatti** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano
Dogecoin
Polkadot
Stellar
Zcash - Pedro Castilho
Monero
Theter
Ripple (XRP) Emanuel N
Binance coin
Bitcoin cash
Theta
Filecoin
TRX
Dai

**Comment by dccsillag** [comment]
corrigido:

Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano
Dogecoin
Polkadot
Stellar
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter
Ripple (XRP) - Emanuel Bissiatti
Binance coin
Bitcoin cash
Theta
Filecoin
TRX
Dai

**Comment by tiagodsilva** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano - Tiago da Silva
Dogecoin
Polkadot
Stellar
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter
Ripple (XRP) - Emanuel Bissiatti
Binance coin
Bitcoin cash
Theta
Filecoin
TRX
Dai

**Comment by RaphaLevy** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano - Tiago da Silva
Dogecoin - Raphael Levy
Polkadot
Stellar
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter
Ripple (XRP) - Emanuel Bissiatti
Binance coin
Bitcoin cash
Theta
Filecoin
TRX
Dai

**Comment by liviameinhardt** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano
Dogecoin
Polkadot
Stellar
Zcash - Pedro Castilho
Monero
Theter
Ripple (XRP) Emanuel Bissiatti
Binance coin
Bitcoin cash
Theta
Filecoin - Lívia
TRX
Dai

**Comment by dccsillag** [comment]
corrigido:

Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano - Tiago da Silva
Dogecoin - Raphael Levy
Polkadot
Stellar
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter
Ripple (XRP) - Emanuel Bissiatti
Binance coin
Bitcoin cash
Theta
Filecoin - Livia
TRX
Dai

**Comment by joao-alcindo** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano - Tiago da Silva
Dogecoin - Raphael Levy
Polkadot - João Alcindo
Stellar
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter
Ripple (XRP) - Emanuel Bissiatti
Binance coin
Bitcoin cash
Theta
Filecoin - Livia
TRX
Dai

**Comment by luizfernando608** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano - Tiago da Silva
Dogecoin - Raphael Levy
Polkadot - João Alcindo
Stellar
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter
Ripple (XRP) - Emanuel Bissiatti
Binance coin
Bitcoin cash - Luiz Luz
Theta
Filecoin - Livia
TRX
Dai

**Comment by lucasmoschen** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano - Tiago da Silva
Dogecoin - Raphael Levy
Polkadot - João Alcindo
Stellar
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter - Lucas Moschen
Ripple (XRP) - Emanuel Bissiatti
Binance coin
Bitcoin cash - Luiz Luz
Theta
Filecoin - Livia
TRX
Dai

**Comment by fccoelho** [comment]
| Apresentação | Data |
---------------------|--------
Ethereum 2.0 - Will Sena | 27/08 
Litecoin  Tarla Lemos | 27/08
Cardano - Tiago da Silva | 27/08
Dogecoin - Raphael Levy | 27/08
Polkadot - João Alcindo | 27/08
Stellar - ? | 3/09
Zcash - Pedro Castilho |  3/09
Monero - Daniel Csillag | 3/09
Theter - Lucas Moschen | 3/09
Ripple (XRP) - Emanuel Bissiatti | 3/09
Bitcoin cash - Luiz Luz | 3/09
Filecoin - Livia | 3/09
Binance coin | 3/09
Theta |
TRX |
Dai |

**Comment by AriOliv** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano - Tiago da Silva
Dogecoin - Raphael Levy
Polkadot - João Alcindo
Stellar
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter - Lucas Moschen
Ripple (XRP) - Emanuel Bissiatti
Binance coin
Bitcoin cash - Luiz Luz
Theta
Filecoin - Livia
TRX
Dai
Hathor -  Ari

**Comment by fccoelho** [comment]
| Apresentação | Data |
---------------------|--------
Ethereum 2.0 - Will Sena | 27/08 
Litecoin  Tarla Lemos | 27/08
Cardano - Tiago da Silva | 27/08
Dogecoin - Raphael Levy | 27/08
Polkadot - João Alcindo | 27/08
Stellar - Lucas Braga | 3/09
Zcash - Pedro Castilho |  3/09
Monero - Daniel Csillag | 3/09
Theter - Lucas Moschen | 3/09
Ripple (XRP) - Emanuel Bissiatti | 3/09
Bitcoin cash - Luiz Luz | 10/09
Filecoin - Livia | 10/09
TRX - João Vinícius | 10/09
Hathor - Ari | 10/09
Binance coin | 10/09
Theta - Victor Bombarda| 10/09 
Dai |

**Comment by jvprimakipr** [comment]
Ethereum 2.0 - William Sena
Litecoin - Tarla Lemos
Cardano - Tiago da Silva
Dogecoin - Raphael Levy
Polkadot - João Alcindo
Stellar - Lucas Braga
Zcash - Pedro Castilho
Monero - Daniel Csillag
Theter - Lucas Moschen
Ripple (XRP) - Emanuel Bissiatti
Binance coin - Erlon Kelvim
Bitcoin cash - Luiz Luz
Theta - Victor Bombarda
Filecoin - Livia
Pi Network - João Vinícius
Dai
Hathor - Ari

**Comment by fccoelho** [comment]
| Apresentação | Data |
---------------------|--------
Ethereum 2.0 - Will Sena | 27/08 
Litecoin  Tarla Lemos | 27/08
Cardano - Tiago da Silva | 27/08
Dogecoin - Raphael Levy | 27/08
Polkadot - João Alcindo | 27/08
Stellar - Lucas Braga | 3/09
Zcash - Pedro Castilho |  3/09
Monero - Daniel Csillag | 3/09
Theter - Lucas Moschen | 3/09
Ripple (XRP) - Emanuel Bissiatti | 3/09
Bitcoin cash - Luiz Luz | 10/09
Filecoin - Livia | 10/09
Pi Network - João Vinícius | 10/09
Hathor - Ari | 10/09
Binance coin - Erlon Kelvim | 10/09
Theta - Victor Bombarda| 10/09 
Audius - Gabriel Machado |10/09
